web:
  resource-path: D:/seo-cms/

spring: 
  datasource: 
    name: dev
    url: jdbc:mysql://192.168.184.131:3306/seo-cms?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
    username: hqsz
    password: 3Aw^dfe2
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.110.51.13
    port: 6379
    timeout: 2000
    jedis:
      pool:
        max-idle: 100
        min-idle: 50
        max-wait: -1

# 日志配置
logging:
  path: D:/seo-cms/logs/
  level:
    root: info              