server:
  port: 8888
  servlet:
    context-path: /

spring:    
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
    favicon:
      enabled: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:${web.resource-path}
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
  servlet: 
    multipart: 
      enabled: true
      file-size-threshold: 0
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        minimum-idle: 10
        idle-timeout: 600000
        max-lifetime: 7200000
        connction-test-query: SELECT 1

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis: 
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.qiuwanchi.cms.entity  # 注意：对应实体类的路径

mapper:
  mappers:
  - cn.qiuwanchi.cms.common.BaseMapper
  not-empty: false
  identity: MYSQL

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false # 如果为true，则分页参数无效的情况下，则查询全部数据
  supportMethodsArguments: true
  params: count=countSql


