web:
  resource-path: /srv/seo/imageVideo/

spring:
  freemarker:
    charset: UTF-8
    #  prefix: classpath:/templates/
    suffix: .ftl
    content-type: text/html
    template-loader-path: classpath:/templates

  mvc:
    static-path-pattern: /**
    resources:
      static-locations: classpath:/static/

  datasource:
    name: dev
    url: jdbc:mysql://127.0.0.1:3306/seo-cms?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: hqsz
    password: 3Aw^dfe2
    driver-class-name: com.mysql.cj.jdbc.Driver

## mybatis mapper文件位置指定
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qiuwanchi.seo.entity
  #  mbatis-log.插件日志输出
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl